name: country_code2
description: Provides list of ISO 3166-1 country codes in enum-like class, as well as parsing and user-assigned code elements

version: 2.0.0
repository: https://github.com/onepub-dev/dart.country

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lint_hard: ^6.1.1
  test: ^1.25.8
  yaml: ^3.1.3
  
topics:
  - country-codes
  - iso-3166-1


